#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
	echo "Please run this script with sudo.";
	exit 1;
fi

cp /etc/nginx/stub /etc/nginx/sites-enabled/$1.conf
sed -i "s/#SITE#/$1/g" /etc/nginx/sites-enabled/$1.conf
