#!/bin/bash

CUR_DIR=$(pwd)

cd $HOME/easyrsa
./easyrsa --batch --req-cn=$1 --days=3650 gen-req $1 nopass
./easyrsa --batch --req-cn=$1 --days=3650 sign-req server $1
echo "Public key path: $HOME/easyrsa/pki/issued/$1.crt"
echo "Private key path: $HOME/easyrsa/pki/private/$1.key"

cd $CUR_DIR
